### ISSUE TITLE
Curry does not let `matches` be an optional argument

### ISSUE THREAD

**Issue by rajatvijay** [nene/f-matches#1]
When we have to just extract the value of the whole field like `extract('value')` and don't want to provide any `matcher` the function is not called since curry has arity as `func.length` by default so it won't call the function until all the arguments have been provided to it. 

The only way now is to do something like: `extract('value', undefined)`

https://github.com/nene/f-matches/blob/261a01a4fa6392bb76c158b7feadb702d81bc870/matches.js#L46

**Comment by nene** [comment]
Indeed. The docs also state that the second parameter should be optional.

I guess there isn't much of a benefit for having this function fully curried:
- I see little point in creating a partial extractor that only has the name parameter filled in.
- I also don't see much use for calling extract() with all three parameters in one go.

At the same time it does look pretty useful to just skip the second parameter to be able to match against anything.

**Comment by nene** [comment]
Then again, making this function uncurried would be inconsistent with the other functions, which I don't really like. I see some alternative options:

- Creating another function to extract anything: `extractAny("myName")`
- Creating another function that matches anything: `extract("myName", matchesAny)`

The latter one would be more descriptive than `extract("myName", undefined)` or `extract("myName", () => true)`

@rajatvijay What do you think of these options?

**Comment by rajatvijay** [comment]
> Creating another function to extract anything: extractAny("myName")

I think `extractAny` seems more straightforward and comfortable. The name is descriptive enough.

> Creating another function that matches anything: extract("myName", matchesAny)

In this, the second argument will be a function that returns true?

**Comment by nene** [comment]
> In this, the second argument will be a function that returns true?

correct.

**Comment by nene** [comment]
OK... I figured that if I'm going to add a helper function, then `extractAny` is probably a better choice, as it allows us to write less code (in contrary to `matchesAny` that would only allow writing different code).

So, released f-matches 1.1 with support for `extractAny`.

Try it out.
